### ISSUE TITLE
Anträge für Straßen ohne Umweldaten

### ISSUE THREAD

**Issue by rastaroko** [ADFC-Hamburg/adfc-tempo30#16]
Nicht für alle Straßen liegen Daten zu Lärm und Abgasen vor. Sofern ein User an einer solchen Straße wohnt, muss er entweder die Möglichkeit haben, einen Antrag ohne diesbezüglich belegte Werte zu verfassen oder er sollte ein Schreiben an die BUE ausgegeben bekommen, in dem er diese dazu auffordert ihm Daten zu Lärm und Abgasen (Stickoxid, PM10, PM2,5) zukommen zu lassen (diese Daten kann man auch via Mail erfragen - muss also nicht unbedingt postalisch erfolgen!). Idealerweise kann er die Daten dann auch noch eingeben, so dass diese dann für die Karte vorliegen.

Hintergrund ist dann  § 13 Abs. 1 HmbTG sowie § 3 Abs. 3 Satz 2 Nr. 1 UIG.

**Comment by tabacha** [comment]
@rastaroko hab jetzt eine Version mit einer Anfrage gebaut. Magst du sie dir bitte ansehen, und mir Rückmeldung geben. Sollte in ca. 5 Minuten (wenn der Build:
https://travis-ci.org/tabacha/adfc-tempo30/builds/175330870 gelaufen ist) auf:
https://tools.adfc-hamburg.de/tempo30/develop/antrag.html zu finden sein (Die Startseite kommt noch anders, du musst eine Straße/Hausnummer eingeben, an der keine/nicht alle Umweltdaten zu finden sind).

**Comment by rastaroko** [comment]
Sorry, bin erst jetzt dazu gekommen. Sieht gut aus. Etwas verwirrend ist, dass bei der Emissionsprüfung erst ?! kommt und man dann auf Antrag prüfen drücken muss. Vielleicht sollte dort schon der Hinweis kommen, dass man die Daten bei der BUE anfordern soll; also im Sinne von "Uns liegen keine Daten für Ihre Wohnung vor. Sie können nun entweder a) Fortfahren und den Antrag ohne Daten stellen oder b) ersteimal Daten bei der BUE anfordern."

Beim der Mailvorlage wäre dann noch ein Copy-Button (wo alles aus dem Feld automatisch kopiert wird -> Text kopieren/ in die Zwischenablage einfügen) oder ein Mail-erstellen-Button (wo gleich eine Mail mit Empfänger, Titel und Inhalt der Mail im Programm des Users erstellt wird) gut.

**Comment by rastaroko** [comment]
Ach so: es steht bei den Emissionswerten noch "Klasse: undef (keine Daten)". kann man das undef einfach rausnehmen? Wäre für den Nutzer m.E. lesbarer...

**Comment by tabacha** [comment]
ich lass das jetzt so, sorry aber das macht echt arbeit, ist zwar evtl. etwas unschön aber das müssen unsere Benutzer ab können.

**Comment by rastaroko** [comment]
Hallo Sven,

 

bin gerade über diese Meldung gestolpert:

 

"Ein Messergebniss 45.2 m von ihrem Haus entfernt zeigt: Der Grenzwert von 20 mg wurde noch nicht erreicht, es ist aber schon viel Feinstaub in der Luft. Mit einem Antrag kann man erreichen, dass die Straßenverkehrsbehörde das ganze genauer prüft. Insbesondere da ab 2020 ein Grenzwerte von 20 mg gelten würde und Sie dann zum einschreiten verpflichtet wäre."

 

Es muss im ersten Teil heißen "25 Mikrogramm"

 

Außerdem ist die Abkürzung für Mikrogramm "μg" oder "Mcg"


 

Gruß

Marcus


Gesendet: Samstag, 26. November 2016 um 19:58 Uhr
Von: "Sven Anders" <notifications@github.com>
An: tabacha/adfc-tempo30 <adfc-tempo30@noreply.github.com>
Cc: rastaroko <marcus.pietsch@gmx.de>, Assign <assign@noreply.github.com>
Betreff: Re: [tabacha/adfc-tempo30] Anträge für Straßen ohne Umweldaten (#16)


Closed #16.
