### ISSUE TITLE
Lärmdaten auf den Häusern sind falsch

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#17]
In der Lärmkarte der Stadt sind die Häuser als weiße Flecken gekennzeichnet. Wir wollen aber die Lärmbelastung außerhalb des Hauses haben. Also  müssen wir irgendwie mitteln

**Comment by tabacha** [comment]
Die folgende Query gibt aus, welche Lärmklassen in der Umgebung gefunden wurden
SELECT klasse, ST_Distance(ST_Transform(ST_GeometryFromText( 'POINT (9.888834 53.471943)',4326), 3857) , ST_Transform(wkb_geometry, 3857)) as d FROM laerm_tag order by d ;

 klasse |        d  
--------+------------------
      5 |                0
      4 | 25.0117483694909
      3 | 41.8221087696409
      2 | 58.6325045111021
      1 | 75.5048280537047

**Comment by tabacha** [comment]
Frage an alle:
Auf dem Beispiel sieht man dass der Mittelpunkt des Hauses (z.B. der Nummer: 116) keinen Lärm abbekommt:
![Laerm Beispiel](https://tools.adfc-hamburg.de/tmp/Laermkarte_Hausnummern.png)

Wie wollen wir damit im Antrag umgehen? Wir könnten eine Tabelle machen, wie weit vom Mittelpunkt des Hauses welcher Lärm ist Wir könnten auch einfach sagen im Umkreis von z.B. 25m  um ein Hausmittelpunkt und nehmen die größte Lärmklasse.

**Comment by rastaroko** [comment]
Ich würde einfach sagen: "An der Straße vor meinem Haus." Die Behörde muss das eh für jeden Antrag neu und individuell berechnen, zumal die Daten aus der Lärmaktionsplanung nicht diejenigen sind, die rechtlich gelten. Das ist daher sowieso nur ein Anhaltspunkt.

**Comment by tabacha** [comment]
SELECT MAX(klasse) FROM laerm_nacht WHERE  ST_Distance(ST_Transform(ST_GeometryFromText( 'POINT (9.820 53.471943)',4326), 3857) , ST_Transform(wkb_geometry, 3857)) < 230;

**Comment by tabacha** [comment]
Zwischenstand: Backend liefert jetzt die Lärmdaten in 25m Umkreis. Allerdings gibt es noch einen Fehler, wenn die Daten nicht gefunden werden (Beispiel: Querstraße 2) Das dazugehörige JSON ist:
"laerm_tag":[{"klasse":null}],"laerm_nacht":[{"klasse":null}]
https://tools.adfc-hamburg.de/tempo30-backend/master/geodaten.php?lat=53.5489951&lon=9.96045054180545

**Comment by tabacha** [comment]
Im Backend gefixt
