### ISSUE TITLE
Erklärung wie der Tempo 30 Antrag funktioniert

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#21]
Es wäre wahrscheinlich gut, den "Antrags-Vorgang" irgndwie im voraus zu kommentieren. Also "was wird abgefragt, was spielt eine Rolle, welche Daten werden erhobenund wo landen die, Einverständnis, dass wir was abbekommen  (von "Nix" über Maildaresse" bis "Name. Anschrift, Daten ... alles"). Sonst beantragen da 100.00 Leute und wir könnten es noch nichtmal merken oder die kontaktieren zu neuen Infos und so. Das müssen wir wohl nochmal durchsprechen.
Außerdem wäre es gut dort auch eine E-Mailaddresse anzugeben, wenn man Probleme mit der Technik oder den Antrag hat

**Comment by tabacha** [comment]
Für den Datenschutz:

Es werden Straße, Hausnummer und Ort an nominatim.openstreetmap.de (OSM Suchdienst) geschickt um eine Hauskoordinate zu bekommen.

Es wird eine Koordinate zur Overpass-Turbo-Api (OSM Anfrage-Dienst) geschickt um die umliegenden Tempo50 Straßen zu finden.

Alle Anfragen finden verschlüsselt statt.

Auf dem ADFC Tools Server wird nur die IP Adresse und der Zugriff gespeichert. Der Antrag selbst wird im Arbeitsspeicher erstellt und sofort nach der Erstellung gelöscht.

**Comment by GeorgSommer** [comment]
Diese Webseite uneterstützt Sie bei der Formulierung eines Antrags auf "verkehrsbeschränkende Maßnahmen"  - also Tempo 30 - für den Bereich Ihres Wohnorts. Die rechtlichen Hintergründe dazu erläutern wir <hier  FIXME.>

<@Sven Gerne nur die Headlines anzeigen, Detail dann jeweils zum "Ausklappen" wenn das ohne all zu viel Aufwand möglich ist.>
Der Antrag basiert auf Lärmdaten und Angabenzur Luftverschmutzung, die die Freie- und Hansestadt Hamburg öffentlich zur Verfügung gestellt hat. (DATENQUELLE, STAND FIXME).

## Adresse angeben

Damit wir diese für Ihren Antrag ermitteln, müssen Sie die Adresse angeben, für die Sie den Antrag stellen möchten. Da die Zuordnung der Adresse nicht immer eindeutig ist, haben SIe auf einer Karte die Gelegenheit,  den gemeinten Standort zu korrigieren.

## Lärm- und Luftwerte prüfen

Nachdem Ihr Standort ermittelt wurde prüft das Programm, ob wivhtige Lärm- und Schadstoffwerte überschritten sind. Sie werden über das Ergebnis informiert und können anschließend den Antragsvordruck abrufen.

## Antragstext bearbeiten, unterschreiben und abschicken

Bitte bearbeiten Sie den Antragstext dann mit einem Textverarbeitungsprogramm (z.B LibreOffice, OpenOffice, MS-Word oder ähnlich). 
Sie müssen dann noch unbedingt Ihren Namen, die Wohnadresse und einige andere Angaben eintragen, bevor Sie den Antrag **zweifach ausdrucken, unterschreiben und an das zuständige Polizeikommissariat senden.** Bitte schicken SIe den Antrag **per Einschreiben** oder geben Sie ihn persönlich ab und lassen sich auf dem zweiten Ausrurck **den Eingang quittieren!**

## ADFC informieren und in Kontakt bleiben

Wir würden uns sehr freuen, wenn Sie uns darüber informieren, dass Sie einen Antrag eingereicht haben und für welche Adresse. Selbstversstädnlich werden wir diese Informationen nicht ohne Ihr Einverständnis an dritte weitergeben!
Wenn Sie uns Ihre E-Mail-Adresse hinterlassen, werden wir Sie gerne weiterhin über aktuelle Entwicklungen zum Thema informieren und Sie auf Wunsch auch mit anderen Antragsteller*Innen - zum Beispiel aus Ihrer Nachbarschaft - in Kontakt bringen.

Sie haben Fragen? Wenden Sie sich an uns  - wir freuen uns über Ihr Interesse!
 Kontakt: tempo30@hamburg.adfc.de

## Datenschutz:

Wir bemühen uns, ausschlißlich die persönlichen Daten zu verarbeiten, die für die Erstellung des Antrags notwendig sind. Außerdem werden persönliche Daten nur dann bei uns gespeichert, wenn Sie dazu Ihr ausdrückliches Einverständnis geben.

## Geodaten ermittelt OpenStreetmap

Zur Ermittlung der Orts- und Umweltbezognen Daten, ist es erforderlich, dass wir diese Angaben von externen Diensten bearbeiten. Alle Anfragen finden verschlüsselt statt, im einzelnen sind dies:
- Es werden Straße, Hausnummer und Ort an nominatim.openstreetmap.de (OSM Suchdienst) geschickt um eine Geo-Koordinate zu bekommen.
- Es wird eine Koordinate zur Overpass-Turbo-Api (OSM Anfrage-Dienst) geschickt um die umliegenden Tempo 50-Straßen zu finden.
  Die Datenschutzbestimmungen zu diesen Diensten finden SIe unter http://wiki.osmfoundation.org/wiki/Privacy_Policy

## ADFC speichert nur Standarddaten

Auf dem ADFC Server, der Ihre Anfrage verarbeitet wird nur die IP Adresse und der Zugriff gespeichert. Der Antrag selbst und die damit verbundenen Daten wird im Arbeitsspeicher erstellt und sofort nach der Erstellung gelöscht.
Die ausführlichen Datenschutzinformationen des ADFC Landesverband Hamburg e.V. finden Sie unter http://hamburg.adfc.de/datenschutzhinweise/
