### ISSUE TITLE
Wollen wir eine Kopie vom Antrag und wenn ja wohin soll diese geschickt werden?

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#22]

**Comment by tabacha** [comment]
Besprochen: 2016-10-12: Wollen wir nach möglichkeit oder eine Rückmeldung dass ein Antrag gestellt wurde, wenn das zu persönlich ist.
Auf einer 3. Seite soll das genauer erklärt werden.

**Comment by JensDx** [comment]
den anteag selbst brauchen wir vermutlich nicht ..wichtig für uns sind aber die informationen
- name
- email / kontaktdaten
- strasse des antragsort
- belastung lärm/luft vorort
- tag der antragstellung(müssen wir im nachgang. z.b eine woche nach download abfragen ..anfängluch auch manuel, später gern automatisch)
- status des antrags ..auch für später relevant..

**Comment by JensDx** [comment]
Kleine bitte, magdt du wenn du so was schließt, wenn noch fragen anrehungen drin stehen ..von dir aus einen abschließenden kommentar einbringen

**Comment by tabacha** [comment]
@JensDx Ja, kann ich machen. Wir speichern jetzt alles was der Anfragende erlaubt. Bis auf die Schadstoffdaten, aber die können wir jederzeit wieder erfragen. Evtl. ist das Ticket damit auch nicht erledigt? Bin mir gerade unsicher.
