### ISSUE TITLE
Gibt es einen Newsletter/Twitter/Facebook?

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#23]
Wie trägt man sich da ein?

**Comment by tabacha** [comment]
Besprochen: 2016-10-12: Ansprechpartner: Läuft Adresse. Twitter+Facebook ADFC-Hamburg

**Comment by JensDx** [comment]
:-) so erfolgreich angemeldet ...

Ich würds gut finden wenn die leute bei der antragsstellung ihre email adresse eingeben können und dann auswählen können was wir damit machen sollen
- zur persönlichen kontakt Aufnahme (fix, nicht abwahlbar)
- newsletter
- straße, name darf für adfc interne daten gespeichert werden(hilfreich bei der betreung/auswertung)
- antragsort darf ohne angabe von name und hausnummer auf der t30 karte  angezeigt werden
