### ISSUE TITLE
Anträge nur für eine Straße 

### ISSUE THREAD

**Issue by rastaroko** [ADFC-Hamburg/adfc-tempo30#24]
Anträge nach der stvo kann man nur für die Straße stellen, an der man direkt wohnt. Es ist auch nicht möglich die Pegel mehrerer Straßen aufzuaddieren, wenn man z. B. in einem Eckhaus wohnt.

Wenn ich meine Straße angebe, werden jedoch 3 verschiedene Straßen zur Auswahl angezeigt. Es sollte jedoch möglichst nur die Anwohnerstraße dargestellt werden.

**Comment by tabacha** [comment]
Wenn du drei Straßen ankreuzt werden drei Anträge generiert. 
Ich hab das so eingebaut, weil es ja Menschen gibt, die an einer Kreuzung von zwei Tempo 50 Straßen wohen. Und die dürfen, soweit ich das weiß auch für beide Straßen Tempo 30 beantragen, wenn beide Straßen dazu führen, dass die Lärmbelastung zu hoch ist.?!?

**Comment by rastaroko** [comment]
Ja, aber nur für jede Straße separat, das sind dann zwei Anträge.

Wenn ich meine Straße und Hausnummer angebe (Heimfelder Straße 56) erhalte ich auch zwei Straßen zur Auswahl, an denen ich überhaupt nicht wohne (Milchgrund und Eißendorfer Pferdeweg). Das ist verwirrend. Außerdem kann es dann leicht passieren, dass sie Leute einfach für irgendwas eine Antrag stellen, weil sie denken, dass sie das dürfen.

Könnte man das nicht so machen, dass man nur für eine Straße zur Zeit einen Antrag stellt und am Ende gefragt wird: "Grenzt ihre Wohnung an eine weitere Straße, für die Sie einen Antrag stellen wollen?"

Man könnte dann ja einfach die Daten aus dem vorherigen Antrag übernehmen und der User müsste nur die Straße ändern...

Gruß 
Marcus

**Comment by tabacha** [comment]
Frage: Wenn ich 200 Meter von einer Tempo 50 Straße wegwohne aber der Lärm von dieser Straße mich krank macht (und z.B. über den Grenzwerten liegt), kann ich dann Tempo 30 beantragen?

Wahrscheinlich reicht es den Umkreis kleiner zu wählen (also z.B. statt 200 Meter Box, nur 100 Meter).  Oder das auf der Seite zu erklären?

Zweimal den Antrag mit unterschiedlichen Straßen herauszurendern ist erheblich einfacher, als den Benutzer wieder in die alten Dialog zu bringen.

Ich erstelle mal eine Version mit 100 Metern.

**Comment by tabacha** [comment]
Naja und Anträge stellen, darf erstmal jeder :-) Es ist ja auch ein Signal, wenn die Behörde öffentlich sagen würde: Es haben 1000 Leute einen Antrag gestellt, aber die mussten wir alle Ablehnen, weil die zuweit weg gewohnt haben.

**Comment by rastaroko** [comment]
Du musst direkt Anwohner der Straße sein, idealerweise gilt also die Wohnadresse.

Vielleicht kann man zumindest nur die Wohnstraße vorauswählen (und den Rest auf der Seite erklären), so dass der Nutzerr sich aktiv dafür entscheiden muss Anträge für weitere Straßen zu stellen?

Was das Antragstellen angeht, wäre ich zurückhaltender. Sonst lesen wir nachher: "ADFC legt Hamburger Behörden mit Unsinnsanträgen lahm." Und auf einmal ist dann der ADFC Schuld, dass Bürger Monate auf Pässe warten müssen und die Polizei Verkehrssünder, wegen Arbeitsüberlastung, nicht bestraft (auch wenn das natürlich nicht stimmt, aber so wird das dann vermutlich laufen). In der Folge würde keiner mehr das Tool nutzen, das Antragstellen und der ADFC wäre diskreditiert und die ganze Arbeit umsonst.

Lange Rede, kurzer Sinn: Wir sollten das möglichst 'sauber' machen.

**Comment by tabacha** [comment]
Überzeugt. 

Auf https://tools.adfc-hamburg.de/tempo30/develop/ ist eine Version mit Umkreis = 100m.

Ich bau dass außerdem noch so um, dass nur die erste gefundene Straße angekreuzt ist und dass es eine Erklärung gibt, dass man Anwohner der Straße sein muss.

**Comment by tabacha** [comment]
Es gibt das Problem, dass ich an dieser Stelle nicht einfach herausfinden kann, ob eine Straße dichter als eine andere ist. Deshalb: wenn zwei oder mehr Straßen gefunden werden, muss man explizit angeben welche gewünscht ist.
