### ISSUE TITLE
Legende+Erklärungen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#26]
Mit Firefox geht es aber.
Mir würde in der Karte jetzt fehlen: Eine Legende, was denn die verschiedenen Farben in den einzelnen Layern bedeuten. Also welche Farbe entspricht welchem Lärmpegel? Was bedeuten die Farben bei den Luftschadstoffen ...
Jemand von den T-30-Leuten müsste dann auch noch einen Text schreiben, der den Sinn und die Funktion der Karte kurz erklärt. So ganz für sich sollten wir sie ja nicht einbinden.

**Comment by JensDx** [comment]
Der ort für die legemde ist zu kläre, ist so was per aufklappendes fenster in der karte sinnvoll/möglich also mit klickfeld wie beim layer und der auswahl dann?

**Comment by tabacha** [comment]
Das ist kein Problem. Machen wir ja z.B. mit dem Antragsfeature zur Zeit

**Comment by tabacha** [comment]
Legende gibt es erstmal
