### ISSUE TITLE
e-Mail Adresse auf Webseite und im Antragsformular laeuft@hamburg.adfc.de

### ISSUE THREAD

**Issue by JensDx** [ADFC-Hamburg/adfc-tempo30#51]
Bitte überall laeuft@hamburg.adfc.de verwenden. 

Die e-Mail Adresse tempo30@ .. möchte ich nur für das Projektwesne verwenden.

**Comment by JensDx** [comment]
@tabacha bitte das Ticket noch mal auf machen. Da ist noch einmal tempo30@ im Antrag drin. Bitte anpassen.

Wie geht es weiter?
Antrag ausfüllen und an Ihre Verhältnisse anpassen. Desto mehr Details Sie angeben, desto schwerer wird es für die Behörde den Antrag abzulehnen. Bei Fragen können Sie uns unter tempo30@hamburg.adfc.de erreichen.

**Comment by tabacha** [comment]
Behoben
