### ISSUE TITLE
Im Antragsformular steht Bezirk HH-Mitte - fix drin?

### ISSUE THREAD

**Issue by JensDx** [ADFC-Hamburg/adfc-tempo30#52]
Im Docx Dokument wird bei mir "Bezirk HH-Mitte" angezeigt obwohl das bei mir Eimsbüttel ist .. steht das im fix Text?

**Comment by tabacha** [comment]
Nachgeschaut auf:
https://github.com/tabacha/adfc-tempo30/blob/master/docx/antrag-tempo30-template.docx

seht {Bezirk}

**Comment by tabacha** [comment]
Gefunden: in js/tempo30/app/create-word.js steht Bezrik Mitte hardcodiert.
