### ISSUE TITLE
Antragstext - Korrekturen

### ISSUE THREAD

**Issue by ghost** [ADFC-Hamburg/adfc-tempo30#60]
Die Überschrift lautet "Antrag auf verkehrsbeschränkende Maßnahmen nach § 45 Abs. 1 Satz 2 Nr. 3 StVO". Diese Stelle im Paragrafen scheint es nicht zu geben. Ich tippe, es muss heißen: "§ 45 Abs. 1 Satz 3 StVO" ABER: Der Paragraf wird weiter unten nochmal verwendet. Wer hat das geschrieben, wer meint, dass es diesen § 45 Abs. 1 Satz 2 Nr. 3 StVO gibt? (Kann ja sein, dass ich mich irre)

überall: Vor einen Doppelpunkt gehört kein Leerzeichen.

Randkommentar:
z.B. “ich kann nicht bei geöffneten Fenster telefonieren, weil es so laut ist”, oder “Ich wache Nachts mehrmals auf, wenn ein LKW vorbeifährt.”
korrigiere in: z.B. “ich kann nicht bei geöffnetem Fenster telefonieren, weil es so laut ist” oder “Ich wache Nachts mehrmals auf, wenn Lkws vorbeifahren.”

Versalien:
BITTE BESCHREIBEN SIE, WELCHE FOLGEN LÄRM UND ABGASE FÜR SIE PERSÖNLICH HABEN:
Diese und andere Versalienzeilen kann ich extrem schlecht lesen. Ich sehe auch nicht, warum hier Dauergroßschrift ist und an anderen Stellen nicht. Ich plädiere für normale Schreibweise.

unverständlich:
[ ] für Kinder werden aufgrund der hohen Geschwindigkeit gefährlich

IST: (z.B. Parkplatzsuche etc.)
SOLL: (z. B. Parkplatzsuche)

meinem/ unserem
bitte ohne Leerzeichen nach dem /
Taucht auch in anderen Zusammenhängen mit dem / im Formular auf.

unverständlich:
Für den Straßenabschnitt vor meinem/ unserem Haus Entfernung wurden folgende Luftdaten 

IST: NO²
SOLL: [Die Ziffer 2 müsste doch tiefergestellt sein.]

(Die Daten beziehen sich auf den nächst verfügbaren Messwert in undefined m Entfernung.)
Hat da etwas nicht funktioniert?!

Hausam
Haus am

liegt die Lärmbelastung im Straßenabschnitt vor meinem/ unserem Hausam Tag in der Klasse: Klasse: 4 also 70-75 dB und in der Nacht in der Klasse: Klasse: 4 also 60-65 dB.
[Das Wort "Klasse" tauch in meinem Formular jeweils doppelt auf.]

bei Erreichen dieser Werte verpflichtet im Ermessenswege
[ich würde nach verpflichtet ein Komma setzen]

ausdrücklich auch zum einem Einschreiten verpflichtet
ausdrücklich auch zum Einschreiten verpflichtet

beantragen wir eine die Prüfung
beantragen wir eine Prüfung

Abgasbelastung auf der Bramfelder Dorfplatz
[hier würde ich schreiben auf der Straße [Straßenbezeichnung] - dann funktioniert es auch bei -platz, -weg, -gasse usw.]

ein sehr hohes Potenzial um den Verkehrslärm
ein sehr hohes Potenzial, um den Verkehrslärm

**Comment by tabacha** [comment]
sollte alles drin sein!?
