### ISSUE TITLE
Verschiedene Seiten nachdem man eine Mail bestätigt hat.

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-tempo30#67]
Nachdem man einen Antrag abgeschickt hat und beim ADFC Daten gespeichert hat (weil man eine oder mehrere Haken gesetzt hat), bekommt man folgende E-Mail:

> Sie haben auf hamburg.adfc.de einen Tempo30 Antrag gestellt. Bitte bestätigen Sie Ihre E-Mail indem Sie auf folgenden Link clicken:
> $url
> Sollten Sie nicht diesen Antrag gestellt haben, ignorieren Sie bitte diese E.-Mail. Fuer Rückfragen stehen wir Ihnen gerne zur Verfügung.
> 
> Ihr ADFC Hamburg

Ich würde gerne wissen, ist der Text gut? Rechtschreibfehler etc.

Was soll passieren, wenn man auf den Link klickt?

Es gibt generell 2 Sachen die dann passieren können:

a) Die URL ist gültig und die E-Mail wird bestätigt.
b) Die URL ist ungültig oder wurde ein zweites mal aufgerufen.

Für beide Fälle sollte eine Webseite auf hamburg.adfc.de angelegt werden und der Link sollte dann dahin verweisen.

**Comment by ghost** [comment]
In deinem Mailtext bitte "klicken" statt "clicken".
Ich würde das mit dem "hat geklappt" oder "hat nicht geklappt" als Unterseiten der Antragsseite anlegen. Das haben wir auf hamburg.adfc.de schon an diversen Stellen ähnlich gemacht.

**Comment by tabacha** [comment]
Ja. Unterseiten muss jemand machen. Freiwillige vor!

**Comment by tabacha** [comment]
Generell gibt es noch das Problem, dass die Umlaute in der E-Mail nicht korrekt codiert sind.

**Comment by tabacha** [comment]
Unterseiten wurden nicht angelegt. Dann bleibt es halt so
