### ISSUE TITLE
Keine Lärmdaten für diese Positon - Lutterothstraße 65

### ISSUE THREAD

**Issue by JensDx** [ADFC-Hamburg/adfc-tempo30#76]
Liegt hier ein Fehler vor oder ist das richitg da meine Hausnummer etwas zurück gesetzt ist? 
Die Distanzregel gilt nicht für Lärm?

(Schritt 3:{"str":"Lutterothstraße","hausnr":"65","plz":"20255","tracking":9580718,"lat":"53.5811448","lon":"9.9487096","polizei":[{"bemerkung":"PK-Grenzen","region":"Eimsbüttel","pk":"PK 23","vd":"VD 2","polizeirev":"23","name":"PK23 Hoheluft","strasse":"Troplowitzstraße 3","plz":"22529","ort":"Hamburg","tel":"040 428 65-2310"}],"ort":[{"bezirk_name":"Eimsbüttel","stadtteil":"Eimsbüttel","ortsteilnummer":"302","bezirk":"3"}],"laerm_tag":[],"laerm_nacht":[],"luftdaten":[{"gid":"14499","name_12":"Methfesselstrae","no2_i1_gb":"41.50644","pm10_i1_gb":"23","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94717639088127 53.5805940114029,9.94737551907786 53.5808348570301,9.94741697034614 53.580905691804,9.94749026906653 53.5810970353211,9.94753975655875 53.5813668277742))","st_distance":"133.967981931754"},{"gid":"14498","name_12":"Methfesselstrae","no2_i1_gb":"40.9248","pm10_i1_gb":"23","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94753975655875 53.5813668277742,9.9475419589565 53.5813788360988))","st_distance":"136.719092990754"},{"gid":"14497","name_12":"Methfesselstrae","no2_i1_gb":"41.13577","pm10_i1_gb":"23.2","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94758141588095 53.5816236536725,9.94766669719607 53.5822407451961))","st_distance":"154.384472114204"},{"gid":"14501","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94682591289677 53.5803131582308,9.9470268170761 53.580468951971,9.94703104883877 53.5804724901296))","st_distance":"225.402833730336"},{"gid":"11630","name_12":"Eidelstedter Weg","no2_i1_gb":"38.05355","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94768322710321 53.5823603507918,9.94795140432352 53.5823411597324,9.9481785142544 53.5823287620284,9.94866767039814 53.5823535666093))","st_distance":"226.229604110723"},{"gid":"11631","name_12":"Eidelstedter Weg","no2_i1_gb":"38.24563","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94866767039814 53.5823535666093,9.94923917208487 53.5823825492084))","st_distance":"226.702753703098"},{"gid":"6792","name_12":"Eidelstedter Weg","no2_i1_gb":"38.24563","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94923917208487 53.5823825492084,9.94979106849204 53.582410536173))","st_distance":"239.459255871562"},{"gid":"6960","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94668926235751 53.5802071906373,9.94682591289677 53.5803131582308))","st_distance":"261.317007842795"},{"gid":"6985","name_12":"Eidelstedter Weg","no2_i1_gb":"37.26376","pm10_i1_gb":"22.2","pm25_i1_gb":"17","st_astext":"MULTILINESTRING((9.94979106849204 53.582410536173,9.95039217314738 53.5824390253357,9.95040914167545 53.5824394022901))","st_distance":"266.124646405639"},{"gid":"11872","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94651525719826 53.5800722561742,9.94668926235751 53.5802071906373))","st_distance":"285.462812037577"},{"gid":"14140","name_12":"Eidelstedter Weg","no2_i1_gb":"37.26376","pm10_i1_gb":"22.2","pm25_i1_gb":"17","st_astext":"MULTILINESTRING((9.95040914167545 53.5824394022901,9.95057117875975 53.5824429995349,9.95078594986006 53.5824327630661,9.95112267895656 53.5823671990201))","st_distance":"307.768055910746"},{"gid":"11627","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94580548960823 53.579482327367,9.94592562434745 53.5795942318648,9.94651525719826 53.5800722561742))","st_distance":"316.406523944054"}]}) V:866e50b

**Comment by tabacha** [comment]
Wir haben das Problem, dass die Lärmdaten auf der Straße schon recht hoch sind, aber an der Nummer 65 keine Lärmdaten vorliegen. Ich vermute dass die Daten auch nur aufgrund der Verkehrsbelastung auf der Methfesselstraße berechnet wurden und für die Lutterothstraße nicht berechnet wurden. Insofern richtig, kein Bug.

**Comment by tabacha** [comment]
@JensDx  magst du das Ticket schließen, wenn es für dich okay ist?

**Comment by tabacha** [comment]
Keine Antwort
