### ISSUE TITLE
Text anpassen Meldung bei keine e-Mailadresse speichern

### ISSUE THREAD

**Issue by JensDx** [ADFC-Hamburg/adfc-tempo30#78]
Wenn Sie diesen Haken entfernen, können wir Sie nicht mehr über wichtige Ereignisse (z.B. dass man noch etwas beantragen muss, Fehler im Antragstext etc.)  benachrichtigen.

Bitte anpassen zu:

Wenn Sie diesen Haken entfernen, können wir Sie nicht durch aktuelle Informationen zum Antragsverfahren unterstützen.  

>>> noch ne kleine Anmerkung ... diesen Text hab ich jetz per hand hier rein kopiert -- automaitsch wird das nicht übergeben oder doch?
(Schritt 4:{"str":"Mengestraße","hausnr":"20","plz":"21107","tracking":2206852,"lat":"53.5003954","lon":"9.99591126992426","polizei":[{"bemerkung":"PK-Grenzen","region":"Harburg","pk":"PK 44","vd":"VD 4","polizeirev":"44","name":"PK44 Wilhelmsburg","strasse":"Georg-Wilhelm-Straße 77","plz":"21107","ort":"Hamburg","tel":"040 428 65-4410"}],"ort":[{"bezirk_name":"Hamburg-Mitte","stadtteil":"Wilhelmsburg","ortsteilnummer":"137","bezirk":"1"}],"laerm_tag":[{"klasse":"1"}],"laerm_nacht":[{"klasse":"1"}],"luftdaten":[{"gid":"4664","name_12":"Mengestrae","no2_i1_gb":"45.68809","pm10_i1_gb":"28.6","pm25_i1_gb":"19.6","st_astext":"MULTILINESTRING((9.99666550603909 53.4993039073564,9.99716134260656 53.4991705080505))","st_distance":"220.851501243583"},{"gid":"4665","name_12":"Mengestrae","no2_i1_gb":"45.68809","pm10_i1_gb":"28.6","pm25_i1_gb":"19.6","st_astext":"MULTILINESTRING((9.99716134260656 53.4991705080505,9.99761480350963 53.4990453599422))","st_distance":"268.166100207622"}],"umweltdaten":{"laerm_tag":{"val_short":"Klasse: 1","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f610.svg\" alt=\"neutraler Smiley\" style=\"width:100px\"/>","val_long":"55-60 dB","description":"Die Lärmwerte sind noch unter der Grenze bei der nachweislich gesundheitliche Beschwerden auftreten. Allerdings hat die Behörde genauere Messerverfahren und kommt evtl. zu anderen Werten. Wenn Sie das Gefühl haben, dass der Lärmpegl hoch ist, stellen Sie gerne einen Antrag."},"laerm_nacht":{"val_short":"Klasse: 1","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f610.svg\" alt=\"neutraler Smiley\" style=\"width:100px\"/>","val_long":"45-50 dB","description":"Die Lärmwerte sind noch unter der Grenze bei der nachweislich gesundheitliche Beschwerden auftreten. Allerdings hat die Behörde genauere Messerverfahren und kommt evtl. zu anderen Werten. Wenn Sie das Gefühl haben, dass der Lärmpegl hoch ist, stellen Sie gerne einen Antrag."},"no2":{"val_short":"45.68809","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f621.svg\" alt=\"böser Smiley\" style=\"width:100px\"/>","val_long":">40","description":"Ein Messergebniss 220.9 m von ihrem Haus entfernt zeigt: Der Grenzwert von 40 mg wurde erreicht oder überschritten. Die Straßenverkehrsbehörde ist zum Einschreiten verpflichtet."},"pm10":{"val_short":"28.6","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f610.svg\" alt=\"neutraler Smiley\" style=\"width:100px\"/>","val_long":">20","description":"Ein Messergebniss 220.9 m von ihrem Haus entfernt zeigt: Der Grenzwert von 40 mg wurde noch nicht erreicht, es ist aber schon viel Feinstaub in der Luft. Mit einem Antrag kann man erreichen, dass die Straßenverkehrsbehörde das ganze genauer prüft."},"pm25":{"val_short":"19.6","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/263a.svg\" alt=\"lachender Smiley\" style=\"width:100px\"/>","val_long":"<30","description":"Ein Messergebniss 220.9 m von ihrem Haus entfernt zeigt: Es ist wenig Feinstaub hier zu finden. Kein Grund einen Antrag zu stellen."}}}) Version:1838048

**Comment by tabacha** [comment]
`
noch ne kleine Anmerkung ... diesen Text hab ich jetz per hand hier rein kopiert -- automaitsch wird das nicht übergeben oder doch?
`
Bei Github-Issue öffnen wird er nicht übertragen. Bei E-Mail eigentlich schon, aber das geht häufig wegen irgendwas im Browser/E-Mailprogramm schief.

**Comment by tabacha** [comment]
@JensDx Bitte mittels Browser Reload die Seite neu laden und testen. Anschließend bitte das Ticket schließen.

**Comment by tabacha** [comment]
-> kein Antwort von Jens: Geschlossen.
