### ISSUE TITLE
Spalten Querstriche fehlen teilweise bei Auswerte Ansicht

### ISSUE THREAD

**Issue by JensDx** [ADFC-Hamburg/adfc-tempo30#80]
siehe Grafik per e-Mail hab das Abbild hier nicht reinbekommen
..
prio c

(Schritt 3:{"str":"Lutterothstraße","hausnr":"65","plz":"20255","tracking":2083227,"lat":53.58136633626079,"lon":9.948701620232894,"polizei":[{"bemerkung":"PK-Grenzen","region":"Eimsbüttel","pk":"PK 23","vd":"VD 2","polizeirev":"23","name":"PK23 Hoheluft","strasse":"Troplowitzstraße 3","plz":"22529","ort":"Hamburg","tel":"040 428 65-2310"}],"ort":[{"bezirk_name":"Eimsbüttel","stadtteil":"Eimsbüttel","ortsteilnummer":"302","bezirk":"3"}],"laerm_tag":[{"klasse":"1"}],"laerm_nacht":[{"klasse":"2"}],"luftdaten":[{"gid":"14498","name_12":"Methfesselstrae","no2_i1_gb":"40.9248","pm10_i1_gb":"23","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94753975655875 53.5813668277742,9.9475419589565 53.5813788360988))","st_distance":"129.114178165915"},{"gid":"14499","name_12":"Methfesselstrae","no2_i1_gb":"41.50644","pm10_i1_gb":"23","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94717639088127 53.5805940114029,9.94737551907786 53.5808348570301,9.94741697034614 53.580905691804,9.94749026906653 53.5810970353211,9.94753975655875 53.5813668277742))","st_distance":"129.338105412351"},{"gid":"14497","name_12":"Methfesselstrae","no2_i1_gb":"41.13577","pm10_i1_gb":"23.2","pm25_i1_gb":"17.8","st_astext":"MULTILINESTRING((9.94758141588095 53.5816236536725,9.94766669719607 53.5822407451961))","st_distance":"133.709407692419"},{"gid":"11630","name_12":"Eidelstedter Weg","no2_i1_gb":"38.05355","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94768322710321 53.5823603507918,9.94795140432352 53.5823411597324,9.9481785142544 53.5823287620284,9.94866767039814 53.5823535666093))","st_distance":"184.765142853899"},{"gid":"11631","name_12":"Eidelstedter Weg","no2_i1_gb":"38.24563","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94866767039814 53.5823535666093,9.94923917208487 53.5823825492084))","st_distance":"185.1537003734"},{"gid":"6792","name_12":"Eidelstedter Weg","no2_i1_gb":"38.24563","pm10_i1_gb":"22.5","pm25_i1_gb":"17.2","st_astext":"MULTILINESTRING((9.94923917208487 53.5823825492084,9.94979106849204 53.582410536173))","st_distance":"199.724849940909"},{"gid":"6985","name_12":"Eidelstedter Weg","no2_i1_gb":"37.26376","pm10_i1_gb":"22.2","pm25_i1_gb":"17","st_astext":"MULTILINESTRING((9.94979106849204 53.582410536173,9.95039217314738 53.5824390253357,9.95040914167545 53.5824394022901))","st_distance":"230.314495389937"},{"gid":"14501","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94682591289677 53.5803131582308,9.9470268170761 53.580468951971,9.94703104883877 53.5804724901296))","st_distance":"250.34749129742"},{"gid":"14140","name_12":"Eidelstedter Weg","no2_i1_gb":"37.26376","pm10_i1_gb":"22.2","pm25_i1_gb":"17","st_astext":"MULTILINESTRING((9.95040914167545 53.5824394022901,9.95057117875975 53.5824429995349,9.95078594986006 53.5824327630661,9.95112267895656 53.5823671990201))","st_distance":"276.796254160311"},{"gid":"6960","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94668926235751 53.5802071906373,9.94682591289677 53.5803131582308))","st_distance":"287.39423282656"},{"gid":"11872","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94651525719826 53.5800722561742,9.94668926235751 53.5802071906373))","st_distance":"312.124290753242"},{"gid":"11627","name_12":"Methfesselstrae","no2_i1_gb":"40.96319","pm10_i1_gb":"22.8","pm25_i1_gb":"17.7","st_astext":"MULTILINESTRING((9.94580548960823 53.579482327367,9.94592562434745 53.5795942318648,9.94651525719826 53.5800722561742))","st_distance":"343.675970360499"}],"umweltdaten":{"laerm_tag":{"val_short":"Klasse: undef","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/2049.svg\" alt=\"?!\" style=\"width:100px\"/>","val_long":"Keine Daten","description":"Wir haben keine Lärmdaten für diese Position"},"laerm_nacht":{"val_short":"Klasse: undef","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/2049.svg\" alt=\"?!\" style=\"width:100px\"/>","val_long":"Keine Daten","description":"Wir haben keine Lärmdaten für diese Position"},"no2":{"val_short":"41.50644","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f621.svg\" alt=\"böser Smiley\" style=\"width:100px\"/>","val_long":">40","description":"Ein Messergebniss 134.0 m von ihrem Haus entfernt zeigt: Der Grenzwert von 40 mg wurde erreicht oder überschritten. Die Straßenverkehrsbehörde ist zum Einschreiten verpflichtet."},"pm10":{"val_short":"23","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/1f610.svg\" alt=\"neutraler Smiley\" style=\"width:100px\"/>","val_long":">20","description":"Ein Messergebniss 134.0 m von ihrem Haus entfernt zeigt: Der Grenzwert von 40 mg wurde noch nicht erreicht, es ist aber schon viel Feinstaub in der Luft. Mit einem Antrag kann man erreichen, dass die Straßenverkehrsbehörde das ganze genauer prüft."},"pm25":{"val_short":"17.8","img":"<img src=\"https://tools.adfc-hamburg.de/tempo30/master/img/263a.svg\" alt=\"lachender Smiley\" style=\"width:100px\"/>","val_long":"<30","description":"Ein Messergebniss 134.0 m von ihrem Haus entfernt zeigt: Es ist wenig Feinstaub hier zu finden. Kein Grund einen Antrag zu stellen."}}}) Version:1838048

**Comment by tabacha** [comment]
@JensDx Das ist ja seltsam. Bekomme ich bei mir nicht nachgestellt. Was für einen Browser/Betriebsystem benutzt du? Irgendwelche Besonderheiten/Plugins etc.?

**Comment by tabacha** [comment]
Keine Antwort -> Geschlossen
