### ISSUE TITLE
Pop Up "Tempo 30 beantragen, Schritt 5: Antrag herunterladen, bearbeiten, unterschreiben und abschicken."

### ISSUE THREAD

**Issue by ghost** [ADFC-Hamburg/adfc-tempo30#83]
(Was ich anzumerken habe, schreibe ich in ###diese Zeichen###)
Sie sollten den Antrag soeben heruntergeladen haben (Dateiname: tempo30-antrag.docx). ###bei mir ist zu diesem Zeitpunkt erst der Downloaddialog sichtbar und wartet auf Bestätigung durch mich###

    Rufen Sie bitte Ihre E-Mails ab. Die Nachricht von uns enthält einen Link, der Sie zur Bestätigung führt. Klicken Sie einfach auf den Link und bestätigen Sie so Ihre Registrierung. ###das verwirrt: Welche Registrierung ist hier gemeint?###
    Bitte vervollständigen Sie den Antrag an den gekennzeichneten Stellen. Wollen Sie die Bearbeitung in einem Schreibprogramm vornehmen, müssen Sie den Antrag zunächst speichern. ###oben steht doch, dass ich das gerade getan hätte?!###
    Ausdrucken
    Unterschreiben
    Abschicken (sollten Sie den Antrag persönlich abgeben, zweimal ausdrucken und den Empfang auf dem einen Exemplar bestätigen lassen) ###muss man das ab "Ausdrucken" wirklich so ausfühlrich schreiben? Die Leute, die sowas ausfüllen, sind doch nicht blöd###
    Abonieren ###Abonnieren### Sie den ADFC Newsletter ###ADFC-Newsletter###
    Erzählen Sie es weiter, z.B. auf Twitter oder Facebook
    Bitte schreiben Sie uns, ob/wie wir den Antrags-Prozess noch besser machen können. ###würde ich weglassen, da ich schon bei jedem Schritt Fehler/Probleme melden kann.###

**Comment by tabacha** [comment]
> (Was ich anzumerken habe, schreibe ich in ###diese Zeichen###)

Das GitHub System versteht Markdown damit kannst du das ganze wesentlich hübscher formatieren.

> Sie sollten den Antrag soeben heruntergeladen haben (Dateiname: tempo30-antrag.docx). ###bei mir ist zu diesem Zeitpunkt erst der Downloaddialog sichtbar und wartet auf Bestätigung durch mich###'

Ja, das ist je nach Browsereinstllung unterschiedlich. Der eine öffnet ein Word, der zweite speichert, der Dritte fragt nach.

> Rufen Sie bitte Ihre E-Mails ab. Die Nachricht von uns enthält einen Link, der Sie zur Bestätigung führt. Klicken Sie einfach auf den Link und bestätigen Sie so Ihre Registrierung. ###das verwirrt: Welche Registrierung ist hier gemeint?###

Hab ich umgebaut zu:  **Rufen Sie bitte Ihre E-Mails ab. Klicken Sie auf den Link und bestätigen Sie so Ihre E-Mailadresse.**

> Bitte vervollständigen Sie den Antrag an den gekennzeichneten Stellen. Wollen Sie die Bearbeitung in  einem Schreibprogramm vornehmen, müssen Sie den Antrag zunächst speichern. ###oben steht doch, dass ich das gerade getan hätte?!###

Mach gerne einen Vorschlag.

> Abschicken (sollten Sie den Antrag persönlich abgeben, zweimal ausdrucken und den Empfang auf dem einen Exemplar bestätigen lassen) ###muss man das ab "Ausdrucken" wirklich so ausfühlrich schreiben? Die Leute, die sowas ausfüllen, sind doch nicht blöd###'

egal, die Leute die nicht blöd sind, lesen das kurz und sagen ist okay.

> Abonieren ###Abonnieren### Sie den ADFC Newsletter ###ADFC-Newsletter###'

korrigiert.

'Bitte schreiben Sie uns, ob/wie wir den Antrags-Prozess noch besser machen können. ###würde ich weglassen, da ich schon bei jedem Schritt Fehler/Probleme melden kann.###'

Lasse ich drinn. Feedback ist immer gut, und der Button unten wird im Zweifel ignoriert.

**Comment by tabacha** [comment]
Die Tippfehler sind in ca. 5 Minuten auf den Develop Stand.

**Comment by ghost** [comment]
Vielleicht könnten wir statt
"Sie sollten den Antrag soeben heruntergeladen haben (Dateiname: tempo30-antrag.docx)."
schreiben
"Unser System hat soeben einen Download (Dateiname: tempo30-antrag.docx) angestoßen. Je nach Browsereinstellung ist der Download schon erfolgt oder Sie müssen ihm in einem Fenster noch zustimmen.
(Ich würde das wirklich so ausführlich schreiben, weil es nur dann korrekt wird und das Downloadfenster u. U. ganz schön versteckt irgendwo aufpoppt).

**Comment by tabacha** [comment]
@garlicvillage den Text finde ich gut. 
Hab ich geändert. Sollte in kürze auf:

https://tools.adfc-hamburg.de/tempo30/develop/antrag.html

testbar sein.

Ich teste das morgen. Wenn es jemand früher testet, gerne bescheid geben, dann kann ich das freigeben.

**Comment by tabacha** [comment]
Sieht nach dem was ich gesehen habe gut aus.
