### ISSUE TITLE
Bestätigungsmail Umlaute korrigieren

### ISSUE THREAD

**Issue by ghost** [ADFC-Hamburg/adfc-tempo30#84]
(Korrekturen ###in diesen Zeichen###)
Sie haben auf hamburg.adfc.de einen Tempo30 Antrag ###Tempo-30-Antrag### gestellt. Bitte bestätigen Sie Ihre E-Mail ##Ihre E-Mail-Adresse, (Komma)### indem Sie auf folgenden Link clicken ###klicken###:
https://tools.adfc-hamburg.de/tempo30-backend/master/validate.php?id=26&secret=BGLnQu
Sollten Sie nicht diesen Antrag gestellt haben, ignorieren Sie bitte diese E.-Mail ###E-Mail###. Fuer ###Für### Rückfragen stehen wir Ihnen gerne zur Verfügung.

Ihr ADFC Hamburg

**Comment by tabacha** [comment]
Umlaute kann die PHP Lösung nicht. Müssen uns mit ue etc. behelfen. Ist unschön aber mehr schaff ich nicht.
Magst du den ganzen Text einmal vollständig richtig hinschreiben, dann kann ich Copy and Paste machen.. Deine Korrekturmarken sind echt nicht so verständlich.

**Comment by ghost** [comment]
NEUER TEXT:
Sie haben auf hamburg.adfc.de einen Tempo-30-Antrag gestellt. Bitte bestätigen Sie Ihre E-Mail-Adresse, indem Sie auf folgenden Link Klicken.:
(((hier der Link)))
Sollten Sie diesen Antrag nicht gestellt haben, ignorieren Sie bitte diese E-Mail. Für Rückfragen stehen wir Ihnen gerne zur Verfügung.

Ihr ADFC Hamburg

Anmerkung zum "ü": Es ist nur in "Fuer" falsch. In "Rückfragen" und "Verfügung" ist es o. k. Du hast also eine Lösung, mit der es funktioniert, dort schon eingebaut.

**Comment by tabacha** [comment]
Leider ist es mit den Umlauten nicht so wie du sagst. Es funktioniert nicht in allen E-Mail-Programmen.

**Comment by tabacha** [comment]
Siehe auch #67

**Comment by tabacha** [comment]
https://github.com/PHPMailer/PHPMailer benutzen wegen Umlaute

**Comment by tabacha** [comment]
Stand: Der Text ist jetzt drinn aber ohne Umlaute.

**Comment by tabacha** [comment]
Stand: Umlaute sind jetzt auch richtig. Auch ohne PHPMailer Produkt
